### ISSUE TITLE
Git Workshop Docs Update

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/docs#73]
- Mention  the consolidated [workshops](https://github.com/kossiitkgp/workshops) and [sandbox](https://github.com/kossiitkgp/sandbox) repositories.
- Update links to old archived repos and point to the new workshops repo instead.
- Update SSH guidelines - SSH cannot be set up on the campus network - use either personal access tokens or the windows login method.
- Mention that in the middle, a mini KOSS intro sem should be conducted so the freshers get to know about KOSS. The main introsem will be conducted later. Highlight why we do this and what we expect from them.
- Add suggested anonymous feedback form fields.

**Comment by harshkhandeparkar** [comment]
@leader282 can you give more details on the SSH point?

**Comment by proffapt** [comment]
> @leader282 can you give more details on the SSH point?

what details do you require?

**Comment by proffapt** [comment]
Just putting my message here for more context regarding the last point.

UPDATE DOCS:
Git and Github must be held around the timeline when gymk societies have their intro seminar, so that we also show our presence during the same time but with a workshop. Usually gymk intro happens by mid of August (+1 week). So it’s best to have git and github workshop done by the end of August.

IMPORTANT:
This git and github workshop will have a significant part, introducing them about KOSS (4-5 slides worth it material). Focusing on when we do selections and why we do it at that time - no need to introduce to open source. Also, other workshops also should have such sections but very small timeline (1-2 slides)
From next time the 2nd point should be considered early and CTMs should be asked to prepare 1 month in advance - because beechmein LT bhi hoga - and they have to actually learn git, so that they can respond to queries.
