### ISSUE TITLE
Add instructions for building the website

### ISSUE THREAD

**Issue by pranitbauva1997** [kossiitkgp/docs#8]
While trying to submit a PR for accounts documentation, I couldn't find instructions to build the website locally. It would be great having this since we can easily test locally before deploying.

**Comment by OrkoHunter** [comment]
Hey Pranit, I am not sure if there is anything like building this repository, since it's all markdown files and GitHub neatly renders them for us.

However, if you mean how it will look on kossiitkgp.org/docs website, then the concerned repository is https://github.com/kossiitkgp/kossiitkgp.org (which is heavily under construction).

I this information can be added in the readme of this repo.
